/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as CicdRouteImport } from './routes/cicd'
import { Route as IndexRouteImport } from './routes/index'

const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const CicdRoute = CicdRouteImport.update({
  id: '/cicd',
  path: '/cicd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cicd': typeof CicdRoute
  '/packages': typeof PackagesRoute
  '/releases': typeof ReleasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cicd': typeof CicdRoute
  '/packages': typeof PackagesRoute
  '/releases': typeof ReleasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cicd': typeof CicdRoute
  '/packages': typeof PackagesRoute
  '/releases': typeof ReleasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cicd' | '/packages' | '/releases'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cicd' | '/packages' | '/releases'
  id: '__root__' | '/' | '/cicd' | '/packages' | '/releases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CicdRoute: typeof CicdRoute
  PackagesRoute: typeof PackagesRoute
  ReleasesRoute: typeof ReleasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cicd': {
      id: '/cicd'
      path: '/cicd'
      fullPath: '/cicd'
      preLoaderRoute: typeof CicdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CicdRoute: CicdRoute,
  PackagesRoute: PackagesRoute,
  ReleasesRoute: ReleasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
